update
Signed-off-by: Guo Ren <ren_guo@c-sky.com>

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -60,28 +60,6 @@ stages:
         expire_in: 7 day
         paths:
             - output/images/
-            
-.localbuild_defconfig: &localbuild_defconfig
-    stage: build
-    tags:
-      - vmh3
-    script:
-    - echo 'Configure Buildroot'
-    - make ${CI_BUILD_NAME}
-    - echo 'Build buildroot'
-    - |
-        make > >(tee build.log |grep '>>>') 2>&1 || {
-            echo 'Failed build last output'
-            tail -200 build.log
-            exit 1
-        }
-    - BUILDROOT_VERSION=$(git log --pretty=oneline|awk 'NR==1'|awk '{print $1}')
-    - if [ -f /root/builds/build_tmp/$BUILDROOT_VERSION/${CI_BUILD_NAME}_test ]; then
-          rm /root/builds/build_tmp/$BUILDROOT_VERSION/${CI_BUILD_NAME}_test; 
-      fi
-    - mkdir -p /root/builds/build_tmp/$BUILDROOT_VERSION/${CI_BUILD_NAME}_test
-    - mv output/host/csky-ci /root/builds/build_tmp/$BUILDROOT_VERSION/${CI_BUILD_NAME}_test
-    - mv output/images /root/builds/build_tmp/$BUILDROOT_VERSION/${CI_BUILD_NAME}_test
 
 csky_gx6605s_defconfig: *defconfig
 csky_gx6605s_fbcon_defconfig: *defconfig
@@ -94,10 +72,6 @@ qemu_csky_ck610_4.16_uclibc_defconfig: *defconfig
 qemu_csky_ck610_4.9_glibc_defconfig: *defconfig
 csky_ck810_sc8925_4.9_glibc_bt_defconfig: *defconfig
 csky_ck860_platform_defconfig: *defconfig
-
-csky_ck610_gx6622_4.16_glibc_bt_defconfig: *localbuild_defconfig
-csky_ck610_gx6622_4.9_uclibc_bt_defconfig: *localbuild_defconfig
-csky_ck807_eragon_4.9_glibc_bt_defconfig: *localbuild_defconfig
 
 qemu_csky_ck810f_4.16_uclibc_defconfig_test:
     stage: test
@@ -183,119 +157,98 @@ qemu_csky_ck610_4.16_uclibc_defconfig_test:
             - test.log
             - test_sum.log
 
-#csky_ck810_sc8925_bt_defconfig_test:
-#    stage: test
-#    tags:
-#      - vmh-sc8925
-#    script:
-#      - echo 'Run test'
-#      - ./output/host/csky-ci/gen_rtb.sh
-#      - touch /home/vmh/workspace/DebugServerConsole/.stamp_gdb_sc8925
-#      - sleep 30
-#      - |
-#          ./output/host/csky-ci/run_test.sh _sc8925 || {
-#              exit 1
-#          }
-#      - touch /home/vmh/workspace/DebugServerConsole/.stamp_gdb_exit_sc8925
-#    dependencies:
-#      - csky_ck810_sc8925_4.9_glibc_bt_defconfig
-#    artifacts:
-#        when: always
-#        expire_in: 2 weeks
-#        paths:
-#            - test.log
-#            - test_sum.log
+#
+# Board local build & test
+#
+.build_local: &build_local
+    - echo 'Configure Buildroot'
+    - make ${CI_BUILD_NAME}
+    - echo 'Build buildroot'
+    - |
+        make > >(tee build.log |grep '>>>') 2>&1 || {
+            echo 'Failed build last output'
+            tail -200 build.log
+            exit 1
+        }
+    - BUILDROOT_VERSION=$(git log --pretty=oneline|awk 'NR==1'|awk '{print $1}')
+    - if [ -f /tmp/gitlab-runner/$BUILDROOT_VERSION/${CI_BUILD_NAME}_test ]; then
+          rm /tmp/gitlab-runner/$BUILDROOT_VERSION/${CI_BUILD_NAME}_test; 
+      fi
+    - mkdir -p /tmp/gitlab-runner/$BUILDROOT_VERSION/${CI_BUILD_NAME}_test
+    - mv output/host/csky-ci /tmp/gitlab-runner/$BUILDROOT_VERSION/${CI_BUILD_NAME}_test
+    - mv output/images /tmp/gitlab-runner/$BUILDROOT_VERSION/${CI_BUILD_NAME}_test
+
+.run_local: &run_local
+    - echo 'Run test'
+    - csky_switch /dev/ttyUSB1 off
+    - sleep 5
+    - csky_switch /dev/ttyUSB1 on
+    - BUILDROOT_VERSION=$(git log --pretty=oneline|awk 'NR==1'|awk '{print $1}')
+    - if [ ! -d /tmp/gitlab-runner/$BUILDROOT_VERSION/${CI_BUILD_NAME} ]; then
+         exit 1;
+      fi
+    - mkdir -p output/host/
+    - cp /tmp/gitlab-runner/$BUILDROOT_VERSION/${CI_BUILD_NAME}/csky-ci output/host/csky-ci -r
+    - cp /tmp/gitlab-runner/$BUILDROOT_VERSION/${CI_BUILD_NAME}/images output/images -r
+    - tar -xf output/images/csky_toolchain_*.tar.xz -C output/host
+    - touch /home/vmh/workspace/DebugServerConsole/.stamp_gdb
+    - sleep 10
+    - |
+        ./output/host/csky-ci/run_test.sh || {
+            exit 1
+        }
+    - touch /home/vmh/workspace/DebugServerConsole/.stamp_gdb_exit
+    - csky_switch /dev/ttyUSB1 off
+
+csky_ck610_gx6622_4.16_glibc_bt_defconfig:
+    stage: build
+    script: *build_local
+    tags:
+      - vmh-ck610-gx-0
+
+csky_ck610_gx6622_4.9_uclibc_bt_defconfig:
+    stage: build
+    script: *build_local
+    tags:
+      - vmh-ck610-gx-0
+
+csky_ck807_eragon_4.9_glibc_bt_defconfig:
+    stage: build
+    script: *build_local
+    tags:
+      - vmh-ck807-eragon-0
 
 csky_ck610_gx6622_4.9_uclibc_bt_defconfig_test:
     stage: test
     tags:
-      - vmh-gx6622
-    script:
-      - echo 'Run test'
-      - /home/vmh/workspace/switch/switch /dev/ttyUSB2 on
-      - BUILDROOT_VERSION=$(git log --pretty=oneline|awk 'NR==1'|awk '{print $1}')
-      - if [ ! -d /root/builds/build_tmp/$BUILDROOT_VERSION/${CI_BUILD_NAME} ]; then
-           exit 1;
-        fi
-      - mkdir -p output/host/
-      - cp /root/builds/build_tmp/$BUILDROOT_VERSION/${CI_BUILD_NAME}/csky-ci output/host/csky-ci -r
-      - cp /root/builds/build_tmp/$BUILDROOT_VERSION/${CI_BUILD_NAME}/images output/images -r
-      - tar -xf output/images/csky_toolchain_*.tar.xz -C output/host
-      - ./output/host/csky-ci/gen_rtb.sh
-      - touch /home/vmh/workspace/DebugServerConsole/.stamp_gdb_gx6622
-      - sleep 30
-      - |
-          ./output/host/csky-ci/run_test.sh _gx6622 || {
-              exit 1
-          }
-      - rm output/images/rootfs output/images/vmlinux output/images/rootfs.* output/images/.gdbinit output/images/*.dtb -rf
-      - touch /home/vmh/workspace/DebugServerConsole/.stamp_gdb_exit_gx6622
-      - /home/vmh/workspace/switch/switch /dev/ttyUSB2 off
+      - vmh-ck610-gx-0
+    script: *run_local 
     dependencies:
       - csky_ck610_gx6622_4.9_uclibc_bt_defconfig
     artifacts:
         when: on_success
         paths:
-            - output/images/
             - test.log
             - test_sum.log
 
 csky_ck610_gx6622_4.16_glibc_bt_defconfig_test:
     stage: test
     tags:
-      - vmh-gx6622
-    script:
-      - echo 'Run test'
-      - /home/vmh/workspace/switch/switch /dev/ttyUSB2 on
-      - BUILDROOT_VERSION=$(git log --pretty=oneline|awk 'NR==1'|awk '{print $1}')
-      - if [ ! -d /root/builds/build_tmp/$BUILDROOT_VERSION/${CI_BUILD_NAME} ]; then
-           exit 1;
-        fi
-      - mkdir -p output/host/
-      - cp /root/builds/build_tmp/$BUILDROOT_VERSION/${CI_BUILD_NAME}/csky-ci output/host/csky-ci -r
-      - cp /root/builds/build_tmp/$BUILDROOT_VERSION/${CI_BUILD_NAME}/images output/images -r
-      - tar -xf output/images/csky_toolchain_*.tar.xz -C output/host
-      - ./output/host/csky-ci/gen_rtb.sh
-      - touch /home/vmh/workspace/DebugServerConsole/.stamp_gdb_gx6622
-      - sleep 30
-      - |
-          ./output/host/csky-ci/run_test.sh _gx6622 || {
-              exit 1
-          }
-      - rm output/images/rootfs output/images/vmlinux output/images/rootfs.* output/images/.gdbinit output/images/*.dtb -rf
-      - touch /home/vmh/workspace/DebugServerConsole/.stamp_gdb_exit_gx6622
-      - /home/vmh/workspace/switch/switch /dev/ttyUSB2 off
+      - vmh-ck610-gx-0
+    script: *run_local 
     dependencies:
       - csky_ck610_gx6622_4.16_glibc_bt_defconfig
     artifacts:
         when: on_success
         paths:
-            - output/images/
             - test.log
             - test_sum.log
 
 csky_ck807_eragon_4.9_glibc_bt_defconfig_test:
     stage: test
     tags:
-      - vmh-eragon
-    script:
-      - echo 'Run test'
-      - BUILDROOT_VERSION=$(git log --pretty=oneline|awk 'NR==1'|awk '{print $1}')
-      - if [ ! -d /root/builds/build_tmp/$BUILDROOT_VERSION/${CI_BUILD_NAME} ]; then
-           exit 1;
-        fi
-      - mkdir -p output/host/
-      - cp /root/builds/build_tmp/$BUILDROOT_VERSION/${CI_BUILD_NAME}/csky-ci output/host/csky-ci -r
-      - cp /root/builds/build_tmp/$BUILDROOT_VERSION/${CI_BUILD_NAME}/images output/images -r
-      - tar -xf output/images/csky_toolchain_*.tar.xz -C output/host
-      - touch /home/vmh/workspace/DebugServerConsole/.stamp_gdb_eragon
-      - sleep 30
-      - |
-          ./output/host/csky-ci/run_test.sh _eragon || {
-              exit 1
-          }
-      - rm output/images/rootfs output/images/vmlinux output/images/rootfs.* output/images/.gdbinit output/images/*.dtb -rf
-      - touch /home/vmh/workspace/DebugServerConsole/.stamp_gdb_exit_eragon
+      - vmh-ck807-eragon-0
+    script: *run_local 
     dependencies:
       - csky_ck807_eragon_4.9_glibc_bt_defconfig
     artifacts:
