csky ci: tempoary store build output locallly for test
Change-Id: Iae72a7c2bb22a2ccae9ed2524e327b31638c7044
Signed-off-by: Mao Han <han_mao@c-sky.com>

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -24,6 +24,7 @@ stages:
 
 .run_test: &run_test
     - echo 'Run test'
+    - tar -vxf output/images/csky_toolchain_*.tar.gz -C output/host
     - |
         ./output/host/csky-ci/run_test.sh || {
             echo 'Failed build last output'
@@ -40,52 +41,43 @@ stages:
         - dl/
     artifacts:
         when: always
-        expire_in: 2 weeks
+        expire_in: 1 day
         paths:
             - output/build/build-time.log
-            - output/host/
-            - output/images/
             - output/build/packages-file-list.txt
+            - output/host/csky-ci
+            - output/host/csky-qemu
+            - output/images/
             - build.log
             
-.localbuild_test_gx6622: &localbuild_test_gx6622
+.localbuild_defconfig: &localbuild_defconfig
     stage: build
     tags:
-      - vmh-gx6622
+      - vmh
     script:
-      - echo 'Configure Buildroot'
-      - make ${CI_BUILD_NAME}
-      - echo 'Build buildroot'
-      - |
+    - echo 'Configure Buildroot'
+    - make ${CI_BUILD_NAME}
+    - echo 'Build buildroot'
+    - |
         make > >(tee build.log |grep '>>>') 2>&1 || {
             echo 'Failed build last output'
             tail -200 build.log
             exit 1
         }
-      - echo 'Run test'
-      - ./output/host/csky-ci/gen_rtb.sh
-      - touch /home/vmh/workspace/DebugServerConsole/.stamp_gdb_gx6622
-      - sleep 30
-      - |
-          ./output/host/csky-ci/run_test.sh _gx6622 || {
-              echo 'Failed build last output'
-              tail -200 test.log
-              exit 1
-          }
-      - touch /home/vmh/workspace/DebugServerConsole/.stamp_gdb_exit_gx6622
-    cache:
-      paths:
-        - dl/
+    - BUILDROOT_VERSION=$(git log --pretty=oneline|head -1|awk '{print $1}')
+    - if [ -f /root/build/build_tmp/$BUILDROOT_VERSION/${CI_BUILD_NAME}_test ]; then
+          rm /root/build/build_tmp/$BUILDROOT_VERSION/${CI_BUILD_NAME}_test; 
+      fi
+    - mkdir -p /root/build/build_tmp/$BUILDROOT_VERSION/${CI_BUILD_NAME}_test
+    - mv output/host/csky-ci /root/build/build_tmp/$BUILDROOT_VERSION/${CI_BUILD_NAME}_test
+    - mv output/image /root/build/build_tmp/$BUILDROOT_VERSION/${CI_BUILD_NAME}_test
     artifacts:
         when: always
-        expire_in: 2 weeks
+        expire_in: 1 day
         paths:
             - output/build/build-time.log
-            - output/images/
             - output/build/packages-file-list.txt
             - build.log
-            - test.log
-            - test_sum.log
 
 csky_gx6605s_defconfig: *defconfig
 csky_gx6605s_fbcon_defconfig: *defconfig
@@ -97,9 +89,9 @@ qemu_csky_ck807_uclibc_bt_defconfig: *defconfig
 qemu_csky_ck610_uclibc_bt_defconfig: *defconfig
 qemu_csky_ck610_glibc_bt_defconfig: *defconfig
 csky_ck810_sc8925_bt_defconfig: *defconfig
+csky_ck610_gx6622_glibc_bt_defconfig: *localbuild_defconfig
+csky_ck610_gx6622_uclibc_bt_defconfig: *localbuild_defconfig
 csky_ck807_eragon_bt_defconfig: *defconfig
-csky_ck610_gx6622_uclibc_bt_defconfig: *localbuild_test_gx6622
-csky_ck610_gx6622_glibc_bt_defconfig: *localbuild_test_gx6622
 
 qemu_csky_ck810_glibc_bt_defconfig_test:
     stage: test
@@ -197,6 +189,66 @@ qemu_csky_ck610_uclibc_bt_defconfig_test:
 #        paths:
 #            - test.log
 #            - test_sum.log
+
+csky_ck610_gx6622_uclibc_bt_defconfig_test:
+    stage: test
+    tags:
+      - vmh-gx6622
+    script:
+      - echo 'Run test'
+      - BUILDROOT_VERSION=$(git log --pretty=oneline|head -1|awk '{print $1}')
+      - if [ ! -f /root/build/build_tmp/$BUILDROOT_VERSION/${CI_BUILD_NAME} ]; then
+           exit 1;
+        fi
+      - cp /root/build/build_tmp/$BUILDROOT_VERSION/${CI_BUILD_NAME}/csky-ci output/host/csky-ci -r
+      - cp /root/build/build_tmp/$BUILDROOT_VERSION/${CI_BUILD_NAME}/image output/image -r
+      - tar -vxf output/images/csky_toolchain_*.tar.gz -C output/host
+      - ./output/host/csky-ci/gen_rtb.sh
+      - touch /home/vmh/workspace/DebugServerConsole/.stamp_gdb_gx6622
+      - sleep 30
+      - |
+          ./output/host/csky-ci/run_test.sh _gx6622 || {
+              echo 'Failed build last output'
+              tail -200 test.log
+              exit 1
+          }
+      - touch /home/vmh/workspace/DebugServerConsole/.stamp_gdb_exit_gx6622
+    artifacts:
+        when: on_success
+        paths:
+            - output/images/
+            - test.log
+            - test_sum.log
+
+csky_ck610_gx6622_glibc_bt_defconfig_test:
+    stage: test
+    tags:
+      - vmh-gx6622
+    script:
+      - echo 'Run test'
+      - BUILDROOT_VERSION=$(git log --pretty=oneline|head -1|awk '{print $1}')
+      - if [ ! -f /root/build/build_tmp/$BUILDROOT_VERSION/${CI_BUILD_NAME} ]; then
+           exit 1;
+        fi
+      - cp /root/build/build_tmp/$BUILDROOT_VERSION/${CI_BUILD_NAME}/csky-ci output/host/csky-ci -r
+      - cp /root/build/build_tmp/$BUILDROOT_VERSION/${CI_BUILD_NAME}/image output/image -r
+      - tar -vxf output/images/csky_toolchain_*.tar.gz -C output/host
+      - ./output/host/csky-ci/gen_rtb.sh
+      - touch /home/vmh/workspace/DebugServerConsole/.stamp_gdb_gx6622
+      - sleep 30
+      - |
+          ./output/host/csky-ci/run_test.sh _gx6622 || {
+              echo 'Failed build last output'
+              tail -200 test.log
+              exit 1
+          }
+      - touch /home/vmh/workspace/DebugServerConsole/.stamp_gdb_exit_gx6622
+    artifacts:
+        when: on_success
+        paths:
+            - output/images/
+            - test.log
+            - test_sum.log
 
 csky_ck807_eragon_bt_defconfig_test:
     stage: test
