cskt ci: combine local build and local test into one step

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -48,9 +48,31 @@ stages:
             - output/build/packages-file-list.txt
             - build.log
             
-.localbuild_defconfig: &localbuild_defconfig
+.localbuild_test_gx6622: &localbuild_test_gx6622
     stage: build
-    script: *build_buildroot
+    tags:
+      - vmh-gx6622
+    script:
+      - echo 'Configure Buildroot'
+      - make ${CI_BUILD_NAME}
+      - echo 'Build buildroot'
+      - |
+        make > >(tee build.log |grep '>>>') 2>&1 || {
+            echo 'Failed build last output'
+            tail -200 build.log
+            exit 1
+        }
+      - echo 'Run test'
+      - ./output/host/csky-ci/gen_rtb.sh
+      - touch /home/vmh/workspace/DebugServerConsole/.stamp_gdb_gx6622
+      - sleep 30
+      - |
+          ./output/host/csky-ci/run_test.sh _gx6622 || {
+              echo 'Failed build last output'
+              tail -200 test.log
+              exit 1
+          }
+      - touch /home/vmh/workspace/DebugServerConsole/.stamp_gdb_exit_gx6622
     tags:
       - vmh
     cache:
@@ -65,6 +87,8 @@ stages:
             - output/images/
             - output/build/packages-file-list.txt
             - build.log
+            - test.log
+            - test_sum.log
 
 csky_gx6605s_defconfig: *defconfig
 csky_gx6605s_fbcon_defconfig: *defconfig
@@ -76,9 +100,9 @@ qemu_csky_ck807_uclibc_bt_defconfig: *defconfig
 qemu_csky_ck610_uclibc_bt_defconfig: *defconfig
 qemu_csky_ck610_glibc_bt_defconfig: *defconfig
 csky_ck810_sc8925_bt_defconfig: *defconfig
-csky_ck610_gx6622_glibc_bt_defconfig: *localbuild_defconfig
-csky_ck610_gx6622_uclibc_bt_defconfig: *localbuild_defconfig
 csky_ck807_eragon_bt_defconfig: *defconfig
+csky_ck610_gx6622_uclibc_bt_defconfig: *localbuild_test_gx6622
+csky_ck610_gx6622_glibc_bt_defconfig: *localbuild_test_gx6622
 
 qemu_csky_ck810_glibc_bt_defconfig_test:
     stage: test
@@ -176,56 +200,6 @@ qemu_csky_ck610_uclibc_bt_defconfig_test:
 #        paths:
 #            - test.log
 #            - test_sum.log
-
-csky_ck610_gx6622_uclibc_bt_defconfig_test:
-    stage: test
-    tags:
-      - vmh-gx6622
-    script:
-      - echo 'Run test'
-      - ./output/host/csky-ci/gen_rtb.sh
-      - touch /home/vmh/workspace/DebugServerConsole/.stamp_gdb_gx6622
-      - sleep 30
-      - |
-          ./output/host/csky-ci/run_test.sh _gx6622 || {
-              echo 'Failed build last output'
-              tail -200 test.log
-              exit 1
-          }
-      - touch /home/vmh/workspace/DebugServerConsole/.stamp_gdb_exit_gx6622
-    dependencies:
-      - csky_ck610_gx6622_uclibc_bt_defconfig
-    artifacts:
-        when: always
-        expire_in: 2 weeks
-        paths:
-            - test.log
-            - test_sum.log
-
-csky_ck610_gx6622_glibc_bt_defconfig_test:
-    stage: test
-    tags:
-      - vmh-gx6622
-    script:
-      - echo 'Run test'
-      - ./output/host/csky-ci/gen_rtb.sh
-      - touch /home/vmh/workspace/DebugServerConsole/.stamp_gdb_gx6622
-      - sleep 30
-      - |
-          ./output/host/csky-ci/run_test.sh _gx6622 || {
-              echo 'Failed build last output'
-              tail -200 test.log
-              exit 1
-          }
-      - touch /home/vmh/workspace/DebugServerConsole/.stamp_gdb_exit_gx6622
-    dependencies:
-      - csky_ck610_gx6622_glibc_bt_defconfig
-    artifacts:
-        when: always
-        expire_in: 2 weeks
-        paths:
-            - test.log
-            - test_sum.log
 
 csky_ck807_eragon_bt_defconfig_test:
     stage: test
