configs: add FBIO_GET_PIXEL_FMT into csky-fb driver
Change-Id: I073e32ad9a15ed04a177c8cd9c175c172a85cec8

diff --git a/board/csky/eragon/fs-overlay/etc/init.d/rcS b/board/csky/eragon/fs-overlay/etc/init.d/rcS
--- a/board/csky/eragon/fs-overlay/etc/init.d/rcS
+++ b/board/csky/eragon/fs-overlay/etc/init.d/rcS
@@ -1,9 +1,14 @@
 #!/bin/sh
 
-echo "rcS"
-mount -t devpts devpts /dev/pts
+# To start mdev
+echo "Starting mdev..."
 echo /sbin/mdev > /proc/sys/kernel/hotplug
 mdev -s
+
+# To start network
+printf "Starting network: "
+/sbin/ifup -a
+[ $? = 0 ] && echo "OK" || echo "FAIL"
 
 #
 # To enable telnetd
